<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Dashboard style -->
<style>
ul[id$=_userMenu]{padding-left:10%}
.nav-pills li.active>a,.nav-pills li.active>a:hover{color:#FFF;background-color:#337AB7}
.nav-pills li>a {border-radius:4px}
nav.customAffix{width:inherit;padding-right:inherit}
#home>.row>.container-fluid>.row>div[class^="col-"]>.container-fluid>.row>div[class^="col-"]:last-child,#home>.row>.container-fluid>.row>div[class^="col-"]>.container-fluid>.row>div[class^="col-"]:first-child{padding-right:0}
#home>.row>.container-fluid>.row>div[class^="col-"]>.container-fluid>.row>div[class^="col-"]:not(:last-child){padding-left:0}
</style>

<!-- Style for PhpMetrics. -->
<style>
.tooltip{position:absolute;background:#333;border-radius:5px;padding:5px 15px;box-shadow:1px 1px 3px;text-align:left;color:#FFF}</style>

<!-- Style for PHPUnit. -->
<style>
.bs-callout{padding:12px;margin:0 0 4px;border:1px solid #eee;border-left-width:6px;border-radius:3px}
.bs-callout-danger{border-left-color:#d9534f}
.bs-callout-warning{border-left-color:#f0ad4e}
.bs-callout-info{border-left-color:#5bc0de}
.bs-callout-success{border-left-color:#5cb85c}
.bs-callout>h4{margin-top:2px}
.bs-callout>hr{margin-bottom:8px;margin-top:8px}
.bs-callout-danger>h4{color:#d9534f}
.bs-callout-warning>h4{color:#f0ad4e}
.bs-callout-info>h4{color:#5bc0de}
.bs-callout-success>h4{color:#5cb85c}
</style>

<!-- Style for PHP CPD. -->
<style>
.phpcpd_snippet>code{padding:0;background-color:inherit}
</style>

<!-- Style for PDepend. -->
<style>
#dashboard_home_panel_pdepend_pyramid>.panel-body{text-align:center}
#dashboard_home_panel_pdepend_pyramid>.panel-body>svg{margin-top:-46px}
#accordion_pdepend ul.dropdown-menu{width:100%}
</style>
